version: '3.4'
services:
     app:
        container_name: pessoa
        image: felipe/pessoa-udemy
        restart: always
        build: ./Pessoa
        working_dir: /Pessoa
        environment:
        volumes:
            - ./Pessoa: /Pessoa
            - ~/ .m2:/root/ .m2 
        ports: 
          - "8082:8082"
        command: mvn clean spring-boot:run
        links:
           - db
        depends_on:
           - db
     db:
      image: felipe/postgresql-pessoa
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        TZ: Americana/Sao_Paulo
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 123
        POSTGRES_DBNAME: postgres
      ports:
       - "5435:5435"
      networks:
        - pessoa-network  
      networks:
         - pessoa-network          
networks:
    pessoa-network:
        driver: bridge
        
