version: '3.1'
services:
    app:
     container_name: pessoa
     image: pessoa4-application
     build: ./
     ports:
      - "8080:8080"
     depends_on:
         - postgres
        
    postgres:
      container_name: pessoa4-springboot-postgresql
      image: postgres
      environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      volumes: 
        - ./postgres:/var/lib/postgresql
      ports:
        - "5433:5433"
